services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komek_by_ticket-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - komek_by_ticket

  nginx:
    image: nginx:alpine
    container_name: komek_by_ticket-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - komek_by_ticket

  mysql:
    image: mysql:8.0
    container_name: komek_by_ticket-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: komek_by_ticket
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
#    command: --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - komek_by_ticket

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: komek_by_ticket-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - komek_by_ticket

volumes:
  mysql_data:

networks:
  komek_by_ticket:
    driver: bridge
    name: komek_by_ticket